[2022-11-20T12:59:16.686+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-11-19T00:00:00+00:00 [queued]>
[2022-11-20T12:59:16.693+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-11-19T00:00:00+00:00 [queued]>
[2022-11-20T12:59:16.693+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-20T12:59:16.693+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-20T12:59:16.694+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-20T12:59:16.701+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): inaccurate> on 2022-11-19 00:00:00+00:00
[2022-11-20T12:59:16.703+0000] {standard_task_runner.py:55} INFO - Started process 79 to run task
[2022-11-20T12:59:16.705+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-11-19T00:00:00+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpkpw8dfb0']
[2022-11-20T12:59:16.706+0000] {standard_task_runner.py:83} INFO - Job 189: Subtask inaccurate
[2022-11-20T12:59:16.744+0000] {task_command.py:376} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-11-19T00:00:00+00:00 [running]> on host 65bebd3e66a2
[2022-11-20T12:59:16.781+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-11-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-19T00:00:00+00:00
[2022-11-20T12:59:16.782+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-20T12:59:16.783+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2022-11-20T12:59:16.788+0000] {subprocess.py:86} INFO - Output:
[2022-11-20T12:59:16.792+0000] {subprocess.py:93} INFO - inaccurate
[2022-11-20T12:59:16.792+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2022-11-20T12:59:16.807+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20221119T000000, start_date=20221120T125916, end_date=20221120T125916
[2022-11-20T12:59:16.838+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-20T12:59:16.848+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
